apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default "vault" .Values.vault.name }}-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::286747865976:role/{{ .Values.vault.iamRoleName }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ default "vault" .Values.vault.name }}-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ default "vault" .Values.vault.name }}-rbac
subjects:
  - kind: ServiceAccount
    name: {{ default "vault" .Values.vault.name }}-sa
    namespace: vault
roleRef:
  kind: Role
  name: {{ default "vault" .Values.vault.name }}-role
  apiGroup: rbac.authorization.k8s.io


      