{{- if .Values.vault.enabled }}
apiVersion: "vault.banzaicloud.com/v1alpha1"
kind: "Vault"
metadata:
  name: "vault"
spec:
  size: {{ default 3 .Values.vault.replicaCount }}
  image: hashicorp/vault:{{ .Values.vault.imageVersion | default "1.14.0" }}
  bankVaultsImage: banzaicloud/bank-vaults:{{ .Values.vault.bankVaultsImageVersion | default "latest" }}
  serviceAccount: vault-sa
  istioEnabled: {{ .Values.vault.istioEnabled | default false }}
  serviceRegistrationEnabled: {{ .Values.vault.serviceRegistrationEnabled | default true }}
  existingTlsSecretName: {{ .Values.vault.existingTlsSecretName | default "vault-bootstrap-tls" }}
  serviceType: ClusterIP
  {{- with .Values.vault.unsealConfig }}
  unsealConfig:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.caNamespaces }}
  caNamespaces:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.vault.config}}
  config:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.vault.volumes }}
  volumes:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.vault.volumeMounts }}
  volumeMounts:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.vault.volumeClaimTemplates }}
  volumeClaimTemplates:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.vault.securityContext }}
  securityContext:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.vault.externalConfig }}
  externalConfig:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.vault.tlsAdditionalHosts }}
  tlsAdditionalHosts:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.vault.affinity }}
  affinity:
    {{ toYaml . | nindent 4 }}
  {{- end }}
{{- end }}



