apiVersion: "vault.banzaicloud.com/v1alpha1"
kind: "Vault"
metadata:
 name: "vault"
spec:
 size: 3
 image: hashicorp/vault:1.19.4
 bankVaultsImage: banzaicloud/bank-vaults:latest

 serviceAccount: vault-sa

 istioEnabled: false

 # Describe where you'd like to store the Vault unseal keys and root token.
 unsealConfig:
   # In this case we are storing the root token and the unseal keys in Kubernetes secrets.
   aws:
    kmsRegion: eu-west-1
    kmsKeyId: 4057cc7f-2252-4db5-adad-4ba236334a66
    s3Bucket: vault-seal-mgmt
    s3Prefix: vault-root
    s3Region: eu-west-1  

 # See https://www.vaultproject.io/docs/configuration/ for more information.
 config:
  # The storage backend to use.
  # TODO: ask BWAG if there use an external storage backend.
  storage:
    raft:
      path: /vault/data
      retry_join:
        # Use the Kubernetes service discovery to find other Vault instances.
        # TODO: learn more about go-discover (The syntax used below) might be useful
        auto_join: provider=k8s label_selector="app.kubernetes.io/name=vault" namespace=vault
        auto_join_ports: 8200
        auto_join_scheme: "https"
  service_registration:
    kubernetes: {}
  log_level: "info"
  log_requests_level: "off"
  log_format: json 
  log_file: /vault/logs/
  log_rotate_bytes: 100000000
  log_rotate_max_files: 9
  # This ensures that vault does not try to lock memory
  # to prevent sensitive secrets from being swapped to disk.
  # TODO: Learn the core to know whay this is a security risk.
  disable_mlock: true

  introspection_endpoint: true
  default_lease_ttl: "1h" 
  max_lease_ttl: "1h"

  listener:
    tcp:
      address: "0.0.0.0:8200"
      cluster_address: "0.0.0.0:8201"
      tls_cert_file: /vault/tls/server.crt
      tls_key_file: /vault/tls/server.key
  ui: true

 # See: https://github.com/banzaicloud/bank-vaults#example-external-vault-configuration for more details.
 externalConfig:
   policies:
   - name: allow_secrets
     rules: path "secret/*" {
             capabilities = ["create", "read", "update", "delete", "list"]
           }

   auth:
   - type: kubernetes
     roles:
       # Allow every pod in the default namespace to use the secret kv store
       - name: default
         bound_service_account_names: default
         bound_service_account_namespaces: default
         policies: allow_secrets
         ttl: 1h
