operator:
  replicaCount: 2
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: karpenter.sh/capacity-type
                operator: In
                values:
                  - spot
  networks: {}

vault:
  enabled: false
  name: vault
  imageVersion: 1.19.4
  bankVaultsImageVersion: "latest"
  replicaCount: 3
  iamRoleName: vault-kms-role
  istioEnabled: false
  unsealConfig: {}
  config: {}
  volumeMounts: []
  volumeClaimTemplates: []
  externalConfig: {}
  affinity: {}
  serviceRegistrationEnabled: true
